### ISSUE TITLE
Why specific redis version is required to run?

### ISSUE THREAD

**Issue by iashraful** [pycasbin/redis-watcher#14]
Why?
```
redis==4.5.2
```

**Comment by hsluoyz** [comment]
@iashraful maybe the developer just tested this version. You are free to test with other versions. If the test goes well, you can make a PR to extend the version range

**Comment by iashraful** [comment]
Here id the PR link: https://github.com/pycasbin/redis-watcher/pull/15

Please release a version if you think that is okay.
